/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "v1.0.0-rc1_qsv-3.3.1-4-g49f74b4"
#endif /* AVUTIL_FFVERSION_H */
